all:
	g++ MTCG4SimOutput_RootConvert.cpp -o MTCG4SimOutput_RootConvert `root-config --cflags --libs`
	g++ MTCG4SimOutput_RootPlot.cpp -o MTCG4SimOutput_RootPlot `root-config --cflags --libs`

convert:
	g++ MTCG4SimOutput_RootConvert.cpp -o MTCG4SimOutput_RootConvert `root-config --cflags --libs`

plot:
	g++ MTCG4SimOutput_RootPlot.cpp -o MTCG4SimOutput_RootPlot `root-config --cflags --libs`

clean:
	rm MTCG4SimOutput_RootConvert
	rm MTCG4SimOutput_RootPlot
