# ----------------------
# Visualization Settings
# ----------------------

### DAWN driver ###
#/vis/open DAWNFILE

### HepRepFile diriver ###
#/vis/open HepRepFile

### OpenGL driver ###
/vis/open OGL 600x600-0+0
#/vis/open OGLIX

#/vis/viewer/set/style wireframe
#/vis/scene/add/axes 0 0 0 1 m

### Add world volume ###
/vis/drawVolume

### Visualise geometry ###
/vis/viewer/set/globalLineWidthScale 2
/vis/viewer/flush

### Set camera angle for OGL driver ###
#/vis/viewer/set/viewpointThetaPhi 70 120

### Trajectory visualisation. ###
### Add trajectories to the visualization. ###
#/vis/scene/add/trajectories
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

### Accumulate multiple events in one picture. ###
#/vis/scene/endOfEventAction accumulate 10

#/vis/viewer/set/background white

#### Trajectory colouring scheme ###
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/set -1 blue
#/vis/modeling/trajectories/drawByCharge-0/set 1 red
#/vis/modeling/trajectories/drawByCharge-0/set 0 green 
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsColour white
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsType circles
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 2
#/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsColour yellow

### Particle ID coloring scheme ###
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
#Yellow
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 255. 255. 0. 1.
#Pink
/vis/modeling/trajectories/drawByParticleID-0/setRGBA proton 255. 192. 203. 1.
#Orange
/vis/modeling/trajectories/drawByParticleID-0/setRGBA deuteron 255. 165. 0. 1.
#Cyan
/vis/modeling/trajectories/drawByParticleID-0/setRGBA C12[0.0] 0. 255. 255. 1.
#Magenta
/vis/modeling/trajectories/drawByParticleID-0/setRGBA Li7[0.0] 255. 0. 255. 1.
#Magenta
/vis/modeling/trajectories/drawByParticleID-0/setRGBA alpha 255. 0. 255. 1.
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsColour white
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType circles
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsColour white
