# --------------------------------------------------------------
# GNUmakefile for mtc simulation.  Michinari Sakai 10/02/23.
# --------------------------------------------------------------

name := mtc
G4TARGET := $(name)
G4EXLIB := true
G4WORKDIR := .

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
