# ----------------
# Run Settings
# ----------------

######################################################################
# Select dopant material of the scintillator for neutron capture enhancement.
# Choose "lithium" or "boron" or "none".
/MTCG4/detector/setNeutronCaptureDopantMaterial boron
#
# Set enrichment fraction of dopant material in scintillator to be 100% or that of
# what is found in natural abundance.
# true: 100%, false: natural abundance.
/MTCG4/detector/setDopantErichment false
#
# Set the fraction of dopant material for neutron capture in the scintillator.
# Available options are those given by Eljen Technology: 0.01, 0.025, 0.05.
/MTCG4/detector/setDopingFraction .05
#
# Apply optical surface properties to photo-sensitive MCP pixels for photon
# detection.
# This allows for certain features of pixels such as quantum efficiency as a
# function of photon wavelength to be used.
# If this feature is turned off, the quantum efficiency will be 100% by default.
# true: turn on, false: turn off
/MTCG4/detector/setOpticalSurfaceProperties true
#
# Place MCPs on all faces of scintillator.
# true: place, false: do not place.
/MTCG4/detector/setMCPPlacement true
#
# Update detector geometry.
# This must be at the end of all detector macro run settings for them
# to take effect.
# (Currenty giving me error, don't use for now.)
/MTCG4/detector/update

######################################################################
# Produce Cerenkov light.
# true: produce, false: do not produce.
/MTCG4/physics/produceCerenkov true
#
# Produce Scintillation light.
# true: produce, false: do not produce.
/MTCG4/physics/produceScintillation true
#
# Take into account chemically bound atoms for thermal neutron scattering.
# true: yes, false: no.
/MTCG4/physics/setNeutronHPThermalScattering true
#
# Set the maximum number of photons produced by the simulation per particle step.
# Available range is from 0 through 1000.
# This is optional.
#/MTCG4/physics/setMaxNumPhotonsPerStep 1000
#
# Set verbosity setting for physics list.
#/MTCG4/physics/setVerbosity 0

######################################################################
# Output only first 30 events.
#/MTCG4/steppingAction/outputOnlyFirst30Events true

######################################################################
# Set incoming neutrino direction.
# Options: +z, random.
/MTCG4/primary/setIncomingNeutrinoDirection +z
#
# Set the neutrino inverse-beta decay interaction vertex in x-y-z coordinate
# space.
# Options: center, random.
/MTCG4/primary/setInverseBetaDecayInteractionVertex center
#
# Flag to read in data to set the initial momentum directions of the primary
# particles with respect to incoming neutrino direction from file
# primaryParticleData.dat.
# true: Initial momentum directions of positron and neutron are that of what is
# read in from file, false: initial momentum directions of positron and neutron
# are that of incoming neutrino.
/MTCG4/primary/readInPrimaryParticleDataFile true
#
# Set the initial kinetic energies (same value for both particles) of positron and
# neutron in units of eV.
# This command is overridden when the command readInPrimaryParticleDataFile is
# set to true.
#/MTCG4/primary/setInverseBetaDecayDaughterParticleKineticEnergy 10000.
#
# Flag to shoot primary positron.
# True: shoot, false: do not shoot.
/MTCG4/primary/shootPrimaryPositron false
#
# Flag to shoot primary neutron.
# True: shoot, false: do not shoot.
/MTCG4/primary/shootPrimaryNeutron true

######################################################################
# Initialize run.
/run/initialize
#
# Set some verbose settings.
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

######################################################################
# Set number of events for this run.
/run/beamOn 30 
